name: CD

on:
  push:
    branches: master

env:
  BUILD_OUTPUT: 'build/Build/Products/Debug'

jobs:

  build:
    
    runs-on: macos-latest

    steps:

    - uses: actions/checkout@v2
      with:
          fetch-depth: '1'

    - name: Install MacKernelSDK
      run: |
        git clone --depth=1 https://github.com/acidanthera/MacKernelSDK.git

    - name: Build itlwm
      run: |
        xcodebuild -scheme itlwm -configuration Debug -derivedDataPath build GIT_COMMIT=_AAAAA | xcpretty && exit ${PIPESTATUS[0]}

    - name: Build AirportItlwm
      run: |
        xcodebuild -scheme "AirportItlwm (all)" -configuration Debug -derivedDataPath build GIT_COMMIT=_AAAAA | xcpretty && exit ${PIPESTATUS[0]}

    - name: Pack Artifacts
      run: |
        cd $BUILD_OUTPUT
          zip -r itlwm-v1-DEBUG-alpha-AAAAA.zip itlwm.kext
          while read -r tgt ; do
            zip -r AirportItlwm-${tgt// /_}-v1-DEBUG-alpha-AAAAA.zip "$tgt"
          done < <(find . -mindepth 1 -maxdepth 1 -type d -not -path "*.kext" | cut -c 3-)
        cd -
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
       name: Debug
       path: "${{ env.BUILD_OUTPUT }}/*.zip"
